services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Use production image (last stage in Dockerfile)
    # and its default command: `node dist/index.js`
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`thirohub.thiro.tech`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=3000"
      - "traefik.http.routers.webserver.entrypoints=websecure"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://thiro:thiro@db:3306/thiro
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: thiro
      MYSQL_USER: thiro
      MYSQL_PASSWORD: thiro
      MYSQL_ROOT_PASSWORD: root
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
